/**
 * Frontend lint rules.
 *
 * `npm run lint` was silently checking nothing — there was no config here, so ESLint
 * reported every file as "ignored because no matching configuration was supplied" and
 * exited zero. A lint script that always passes is worse than no lint script.
 */
import js from '@eslint/js';
import globals from 'globals';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';

export default [
  { ignores: ['dist/**', 'node_modules/**'] },
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.browser },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    settings: { react: { version: 'detect' } },
    plugins: { react, 'react-hooks': reactHooks },
    rules: {
      ...react.configs.flat.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      // The new JSX transform: React is not in scope and does not need to be.
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      // An unused caught error is the documented way to say "this failure is expected
      // and handled by falling through" — it appears throughout the storage helpers.
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrors: 'none' }],
    },
  },
  {
    // Vendored components: shadcn/ui and Magic UI, generated by their CLI into this
    // directory and intended to be used as-is. eslint-plugin-react-hooks v7 ships the
    // React Compiler's strictness rules (no ref reads during render, no impure calls
    // during render, no setState in an effect) and several of these upstream files
    // trip them by design — particles reads canvas refs in render, dot-pattern mints an
    // SVG id with Math.random(). Rewriting library code to satisfy a linter defeats the
    // point of taking the library. Everything the project authors itself keeps the
    // full rule set; only this directory is exempt, and only from those three rules.
    files: ['src/components/ui/**/*.{js,jsx}'],
    rules: {
      'react-hooks/refs': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    // The crypto conformance test is a Node script that lives beside the module it
    // checks so the two cannot drift apart. It runs under Node, not in a browser.
    files: ['src/**/*.test.mjs'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
];
