import env from './backend/config/env.js';
import mongoose from 'mongoose';
const conn = await mongoose.connect(env.MONGO_URI, { dbName: env.MONGO_DB_CORE, serverSelectionTimeoutMS: 15000 });
const db = conn.connection.db;
const core = (n) => db.collection(n);
const cases = await core('cases').find({}, { projection: { firNumber:1, stage:1, courtId:1, cnrNumber:1, courtName:1, chargesheetFiledOn:1, stationCode:1, jurisdictionComputed:1, sensitivityClass:1, maxPunishmentYears:1 } }).toArray();
console.log('CASES', JSON.stringify(cases, null, 1));
const users = await core('users').find({}, { projection: { authorityId:1, authority:1, role:1, scope:1, name:1 } }).toArray();
console.log('USERS', JSON.stringify(users));
const certs = await core('certificates').aggregate([{ $group: { _id: '$evidenceId', n: { $sum: 1 }, signatures: { $push: { $size: '$signatures' } } } }]).toArray();
console.log('CERTS per evidence', JSON.stringify(certs));
const evCount = await core('evidence').aggregate([{ $group: { _id: '$caseId', n: { $sum: 1 }, pr: { $push: '$triage.priority' }, fs: { $push: '$forensic.status' } } }]).toArray();
console.log('EVIDENCE per case', JSON.stringify(evCount));
const custody = await core('custody_items').find({}, { projection: { itemCode:1, caseId:1, status:1, currentLocation:1, frozen:1, pendingTransfer:1, evidenceId:1 } }).toArray();
console.log('CUSTODY', JSON.stringify(custody));
const refs = await core('referrals').find({}, { projection: { exhibitCode:1, status:1, labId:1, caseId:1 } }).toArray();
console.log('REFERRALS', JSON.stringify(refs));
const vak = await core('vakalatnama_filings').find({}, { projection: { caseId:1, status:1, courtId:1, advocateAuthorityId:1 } }).toArray();
console.log('VAKALATNAMA', JSON.stringify(vak));
const dirCourt = conn.connection.client.db('dir_court');
console.log('DIR LISTINGS', JSON.stringify(await dirCourt.collection('case_listings').find().toArray()));
console.log('DIR COURTS', JSON.stringify(await dirCourt.collection('courts').find({}, {projection:{code:1,courtType:1,designations:1}}).toArray()));
const dbs = await conn.connection.client.db().admin().listDatabases().catch(e => ({ err: e.message }));
console.log('DBS', JSON.stringify(dbs.databases?.map(d=>d.name) ?? dbs));
const ledgerTail = await core('ledger').find({}, { projection: { seq:1, eventType:1, caseId:1, payload:1, occurredAt:1 } }).sort({ seq: -1 }).limit(25).toArray();
console.log('LEDGER TAIL', JSON.stringify(ledgerTail));
await mongoose.disconnect();
