/**
 * Merkle batching and anchoring to Arbitrum Sepolia.
 *
 * These run in DRY_RUN (no signing key), which exercises the whole pipeline —
 * batching, root computation, idempotency guards, entry stamping and proof
 * verification — without submitting a transaction.
 *
 * The on-chain half is verified separately and for real by
 * `contracts/scripts/cross-check-backend-merkle.js`, which deploys LexxAnchor and
 * checks that proofs generated by THIS code verify ON THE CONTRACT at nine tree
 * sizes. Splitting it this way keeps the fast suite fast while still proving the
 * integration that would otherwise fail silently.
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import request from 'supertest';
import { allModels } from '../../models/index.js';
import { Ledger } from '../../models/Ledger.js';
import { AnchorBatch } from '../../models/AnchorBatch.js';
import { createApp } from '../../app.js';
import { appendEvent, verifyChain } from '../../services/ledger.js';
import { runAnchorCycle, verifyAnchoredEntry, latestAnchor, computeBatchId } from '../../services/anchor.js';
import { merkleRoot } from '../../services/merkle.js';
import { LEDGER_EVENT, ANCHOR_STATUS, ANCHOR_NETWORK, ANCHOR_CHAIN_ID } from '../../models/enums.js';

let mongo;
let server;

beforeAll(async () => {
  mongo = await MongoMemoryServer.create();
  await mongoose.connect(mongo.getUri(), { dbName: 'lexx_test_anchor', bufferCommands: false });
  for (const m of allModels) await m.createIndexes();
  server = createApp();
}, 120_000);

afterAll(async () => {
  await mongoose.disconnect();
  await mongo.stop();
});

beforeEach(async () => {
  await Promise.all(Object.values(mongoose.connection.collections).map((c) => c.deleteMany({})));
});

const addEvents = async (n) => {
  for (let i = 0; i < n; i += 1) {
    await appendEvent({
      eventType: LEDGER_EVENT.CASE_CREATED,
      payload: { i, note: `event ${i}` },
    });
  }
};

// ================================================================= batching ==

describe('anchor batching', () => {
  it('does nothing when there is nothing to anchor', async () => {
    const res = await runAnchorCycle();
    expect(res.batched).toBe(false);
    expect(res.reason).toBe('NOTHING_TO_ANCHOR');
  });

  it('batches unanchored entries and computes the root', async () => {
    await addEvents(5);
    const res = await runAnchorCycle();

    expect(res.batched).toBe(true);
    expect(res.batch.fromSeq).toBe(1);
    expect(res.batch.toSeq).toBe(5);
    expect(res.batch.leafCount).toBe(5);
    expect(res.batch.merkleRoot).toMatch(/^0x[0-9a-f]{64}$/);
  });

  it('records MONAD TESTNET, never Ethereum Sepolia', async () => {
    await addEvents(3);
    const { batch } = await runAnchorCycle();

    expect(batch.network).toBe(ANCHOR_NETWORK);
    expect(batch.network).toBe('monad-testnet');
    expect(batch.chainId).toBe(ANCHOR_CHAIN_ID);
    expect(batch.chainId).toBe(10143);
    // Ethereum Sepolia's chain id must appear nowhere.
    expect(batch.chainId).not.toBe(11155111);
  });

  it('stamps the batched entries so they are not re-anchored', async () => {
    await addEvents(4);
    const { batch } = await runAnchorCycle();

    const entries = await Ledger.find().sort({ seq: 1 }).lean();
    expect(entries.every((e) => e.anchorBatchId === batch.batchId)).toBe(true);

    const second = await runAnchorCycle();
    expect(second.batched).toBe(false);
    expect(second.reason).toBe('NOTHING_TO_ANCHOR');
  });

  it('anchors only NEW entries on the next cycle', async () => {
    await addEvents(3);
    const first = await runAnchorCycle();
    await addEvents(2);
    const second = await runAnchorCycle();

    expect(first.batch.toSeq).toBe(3);
    expect(second.batch.fromSeq).toBe(4);
    expect(second.batch.toSeq).toBe(5);
  });

  it('runs in DRY_RUN with no signing key, and says so honestly', async () => {
    await addEvents(2);
    const res = await runAnchorCycle();

    expect(res.batch.status).toBe(ANCHOR_STATUS.DRY_RUN);
    expect(res.batch.txHash).toBeNull();
    // A dry run is its own state, not a silent success.
    expect(res.batch.status).not.toBe(ANCHOR_STATUS.CONFIRMED);
  });

  it('respects the batch size limit', async () => {
    await addEvents(10);
    const res = await runAnchorCycle({ limit: 4 });
    expect(res.batch.leafCount).toBe(4);
    expect(res.batch.toSeq).toBe(4);
  });

  it('leaves the ledger chain intact', async () => {
    await addEvents(6);
    await runAnchorCycle();
    expect((await verifyChain()).intact).toBe(true);
  });
});

// ============================================================= idempotency ===

describe('anchor idempotency — a batch may be anchored exactly once', () => {
  it('derives a deterministic batch id from the sequence range', () => {
    expect(computeBatchId(1, 10)).toBe(computeBatchId(1, 10));
    expect(computeBatchId(1, 10)).not.toBe(computeBatchId(1, 11));
    expect(computeBatchId(1, 10)).toMatch(/^0x[0-9a-f]{64}$/);
  });

  it('refuses a second batch over the same sequence range', async () => {
    await addEvents(3);
    const first = await runAnchorCycle();
    expect(first.batched).toBe(true);

    // Simulate a crashed run: entries un-stamped, but the batch row exists.
    await Ledger.collection.updateMany({}, { $set: { anchorBatchId: null } });

    const second = await runAnchorCycle();
    expect(second.batched).toBe(false);
    expect(second.reason).toBe('BATCH_ALREADY_EXISTS');
    expect(await AnchorBatch.countDocuments()).toBe(1);
  });

  it('enforces uniqueness at the database level too', async () => {
    await addEvents(2);
    const { batch } = await runAnchorCycle();

    await expect(
      AnchorBatch.create({
        batchId: '0xdifferent',
        fromSeq: batch.fromSeq,
        toSeq: batch.toSeq,
        leafCount: 1,
        merkleRoot: '0x' + 'a'.repeat(64),
      })
    ).rejects.toThrow();
  });

  it('refuses a duplicate batchId', async () => {
    await addEvents(2);
    const { batch } = await runAnchorCycle();

    await expect(
      AnchorBatch.create({
        batchId: batch.batchId,
        fromSeq: 900,
        toSeq: 901,
        leafCount: 1,
        merkleRoot: '0x' + 'b'.repeat(64),
      })
    ).rejects.toThrow();
  });
});

// ============================================================== verification ==

describe('anchor verification', () => {
  it('proves an entry is committed to by the published root', async () => {
    await addEvents(7);
    await runAnchorCycle();

    for (const seq of [1, 4, 7]) {
      const result = await verifyAnchoredEntry(seq);
      expect(result.ok).toBe(true);
      expect(result.publishedRoot).toBe(result.computedRoot);
      expect(Array.isArray(result.proof)).toBe(true);
    }
  });

  it('reports NOT_ANCHORED for an entry with no batch', async () => {
    await addEvents(2);
    const result = await verifyAnchoredEntry(1);
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('NOT_ANCHORED');
  });

  it('DETECTS a ledger entry altered AFTER anchoring — the whole point', async () => {
    await addEvents(5);
    const { batch } = await runAnchorCycle();

    // Tamper at the database level, as an attacker with DB access would.
    await mongoose.connection
      .collection('ledger')
      .updateOne({ seq: 3 }, { $set: { entryHash: 'f'.repeat(64) } });

    const result = await verifyAnchoredEntry(1);
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('ROOT_MISMATCH');
    expect(result.computedRoot).not.toBe(batch.merkleRoot);
  });

  it('recomputes the same root from the stored leaf hashes', async () => {
    await addEvents(6);
    const { batch } = await runAnchorCycle();
    expect(merkleRoot(batch.leafHashes)).toBe(batch.merkleRoot);
  });
});

// ============================================================ public surface ==

describe('GET /api/anchors/latest — public', () => {
  it('reports honestly when nothing is anchored', async () => {
    const res = await request(server).get('/api/anchors/latest');
    expect(res.status).toBe(200);
    expect(res.body.anchored).toBe(false);
  });

  it('publishes the root and chain facts without authentication', async () => {
    await addEvents(3);
    await runAnchorCycle();

    const res = await request(server).get('/api/anchors/latest');
    expect(res.status).toBe(200);
    expect(res.body.anchored).toBe(true);
    expect(res.body.merkleRoot).toMatch(/^0x[0-9a-f]{64}$/);
    expect(res.body.network).toBe('monad-testnet');
    expect(res.body.chainId).toBe(10143);
  });

  it('publishes NO leaf hashes, payloads or case identifiers', async () => {
    await addEvents(3);
    await runAnchorCycle();

    const res = await request(server).get('/api/anchors/latest');
    const body = JSON.stringify(res.body);

    // A root is a commitment. Publishing the leaves would disclose the ledger's
    // shape and volume, which is exactly what the root exists to avoid.
    expect(res.body.leafHashes).toBeUndefined();
    expect(body).not.toMatch(/payload|caseId|entryHash/);
  });

  it('exposes a Monad Testnet explorer link once a transaction exists', async () => {
    await addEvents(2);
    const { batch } = await runAnchorCycle();

    await AnchorBatch.updateOne(
      { batchId: batch.batchId },
      { $set: { txHash: '0x' + 'c'.repeat(64), status: ANCHOR_STATUS.CONFIRMED } }
    );

    const anchor = await latestAnchor();
    expect(anchor.explorerUrl).toContain('testnet.monadexplorer.com');
    expect(anchor.explorerUrl).toContain('/tx/0x');
  });
});

// ========================================================== failure handling ==

describe('anchor failure handling', () => {
  it('never marks a batch CONFIRMED without a receipt', async () => {
    await addEvents(2);
    const { batch } = await runAnchorCycle();
    // DRY_RUN is the honest state when nothing was submitted.
    expect(batch.status).toBe(ANCHOR_STATUS.DRY_RUN);

    const stored = await AnchorBatch.findOne({ batchId: batch.batchId }).lean();
    expect(stored.txHash).toBeNull();
    expect(stored.blockNumber).toBeNull();
  });

  it('keeps a FAILED batch out of the public latest-anchor endpoint', async () => {
    await addEvents(2);
    const { batch } = await runAnchorCycle();
    await AnchorBatch.updateOne(
      { batchId: batch.batchId },
      { $set: { status: ANCHOR_STATUS.FAILED, failureReason: 'TRANSACTION_REVERTED' } }
    );

    const anchor = await latestAnchor();
    expect(anchor).toBeNull();
  });
});
